import React, { useEffect, useMemo, useState } from 'react';
import { FileDown, Pencil, Plus, Printer, XCircle } from 'lucide-react';
import { DataTable } from '../components/DataTable';
import { useAuth } from '../components/AuthContext';
import { Button, Card, Confirm, Form, Input, Loading, Modal, PageHeader, SearchInput, Select, StatusBadge, Textarea } from '../components/ui';
import { useToast } from '../components/Toast';
import { escapeHtml, paymentLabels, today } from '../lib/utils';

const newEmpty=()=>({operation_token:crypto.randomUUID(),receipt_number:'',customer_id:'',receivable_id:'',amount:'',commission_percentage:'',collection_date:today(),payment_method:'cash',notes:''});
export default function CollectionsPage(){
 const {money,can,settings}=useAuth();const toast=useToast();
 const [rows,setRows]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[receivables,setReceivables]=useState<any[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true);
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<any|null>(null),[form,setForm]=useState<any>(newEmpty()),[saving,setSaving]=useState(false),[cancel,setCancel]=useState<any|null>(null),[reason,setReason]=useState('');
 const load=async()=>{setLoading(true);try{const [r,c,rv]=await Promise.all([window.nexora.collections.list({search}),window.nexora.customers.list({status:'active'}),window.nexora.receivables.list({})]);setRows(r);setCustomers(c);setReceivables(rv.filter((x:any)=>x.status!=='paid'&&x.status!=='cancelled'));}catch(e:any){toast.error(e.message)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[search]);
 const available=useMemo(()=>receivables.filter(r=>!form.customer_id||String(r.customer_id)===String(form.customer_id)),[receivables,form.customer_id]);
 const chosen=receivables.find(r=>String(r.id)===String(form.receivable_id));
 const calc=useMemo(()=>{const amount=Number(form.amount||0),p=Number(form.commission_percentage||chosen?.commission_percentage||0),commission=amount*p/100;return{commission,net:amount-commission}},[form.amount,form.commission_percentage,chosen]);
 const showCreate=()=>{setEditing(null);setForm(newEmpty());setOpen(true)};
 const save=async()=>{setSaving(true);try{const v={...form,customer_id:Number(form.customer_id),receivable_id:Number(form.receivable_id),commission_percentage:form.commission_percentage===''?undefined:Number(form.commission_percentage)};editing?await window.nexora.collections.update(editing.id,v):await window.nexora.collections.create(v);toast.success(editing?'تم تعديل عملية القبض.':'تم تسجيل عملية القبض.');setOpen(false);await load();}catch(e:any){toast.error(e.message)}finally{setSaving(false)}};
 const doCancel=async()=>{if(!cancel)return;setSaving(true);try{await window.nexora.collections.cancel(cancel.id,reason);toast.success('تم إلغاء عملية القبض وإعادة احتساب الرصيد.');setCancel(null);setReason('');await load();}catch(e:any){toast.error(e.message)}finally{setSaving(false)}};
 const printReceipt=async(id:number)=>{try{const {receipt,settings:s}=await window.nexora.collections.receipt(id);const html=`<h1>${escapeHtml(s.organization_name)}</h1><h2>إيصال قبض رقم ${escapeHtml(receipt.receipt_number)}</h2><div class="meta"><span>التاريخ: ${escapeHtml(receipt.collection_date)}</span><span>طريقة الدفع: ${escapeHtml(paymentLabels[receipt.payment_method]||receipt.payment_method)}</span></div><table><tbody><tr><th>العميل</th><td>${escapeHtml(receipt.customer_name)}</td></tr><tr><th>المندوب</th><td>${escapeHtml(receipt.representative_name||'—')}</td></tr><tr><th>المبلغ المستحق</th><td>${escapeHtml(receipt.receivable_number)} — ${escapeHtml(receipt.receivable_description)}</td></tr><tr><th>المبلغ المقبوض</th><td>${escapeHtml(money(receipt.amount))}</td></tr><tr><th>نسبة المندوب</th><td>${escapeHtml(receipt.commission_percentage)}%</td></tr><tr><th>قيمة العمولة</th><td>${escapeHtml(money(receipt.commission_amount))}</td></tr><tr><th>صافي الإدارة</th><td>${escapeHtml(money(receipt.net_amount))}</td></tr><tr><th>ملاحظات</th><td>${escapeHtml(receipt.notes||'—')}</td></tr></tbody></table><p style="margin-top:40px;text-align:left">المستلم: ${escapeHtml(receipt.created_by_name||'')}</p>`;await window.nexora.export.pdf(`إيصال-${receipt.receipt_number}`,html);toast.success('تم إنشاء ملف PDF للإيصال.');}catch(e:any){toast.error(e.message)}};
 return <><PageHeader title="عمليات القبض" subtitle="تسجيل الدفعات الجزئية أو الكاملة وحساب عمولة المندوب تلقائياً" actions={can('collections','create')&&<Button onClick={showCreate}><Plus size={17}/>تسجيل قبض</Button>}/>
 <Card><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="بحث برقم الإيصال أو العميل"/></div>{loading?<Loading/>:<DataTable rows={rows} columns={[
  {key:'receipt_number',header:'الإيصال'},{key:'collection_date',header:'التاريخ'},{key:'customer_name',header:'العميل'},{key:'representative_name',header:'المندوب'},{key:'receivable_number',header:'المستحق'},
  {key:'amount',header:'المبلغ',render:r=>money(r.amount)},{key:'commission_percentage',header:'النسبة',render:r=>`${r.commission_percentage}%`},{key:'commission_amount',header:'العمولة',render:r=>money(r.commission_amount)},{key:'net_amount',header:'الصافي',render:r=>money(r.net_amount)},
  {key:'payment_method',header:'الدفع',render:r=>paymentLabels[r.payment_method]||r.payment_method},{key:'status',header:'الحالة',render:r=><StatusBadge status={r.status}/>},{key:'actions',header:'الإجراءات',render:r=><div className="row-actions"><button onClick={()=>void printReceipt(r.id)} title="PDF"><Printer size={17}/></button>{can('collections','edit')&&r.status==='active'&&<button onClick={()=>{setEditing(r);setForm({...r,customer_id:String(r.customer_id),receivable_id:String(r.receivable_id),amount:String(r.amount),commission_percentage:String(r.commission_percentage)});setOpen(true)}}><Pencil size={17}/></button>}{can('collections','delete')&&r.status==='active'&&<button className="danger" onClick={()=>setCancel(r)}><XCircle size={17}/></button>}</div>}
 ]}/>}</Card>
 <Modal open={open} title={editing?'تعديل عملية قبض':'تسجيل عملية قبض'} onClose={()=>setOpen(false)}><Form onSubmit={save}><div className="form-grid">
  <Input label="رقم الإيصال" placeholder="يُنشأ تلقائياً" value={form.receipt_number||''} onChange={e=>setForm({...form,receipt_number:e.target.value})}/><Input label="تاريخ القبض" type="date" required value={form.collection_date} onChange={e=>setForm({...form,collection_date:e.target.value})}/>
  <Select label="العميل *" required disabled={!!editing} value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value,receivable_id:''})}><option value="">اختر العميل</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select>
  <Select label="المبلغ المستحق *" required disabled={!!editing} value={form.receivable_id} onChange={e=>{const r=receivables.find(x=>String(x.id)===e.target.value);setForm({...form,receivable_id:e.target.value,commission_percentage:r?String(r.commission_percentage):''})}}><option value="">اختر السجل</option>{available.map(r=><option key={r.id} value={r.id}>{r.number} — المتبقي {money(r.remaining_amount)}</option>)}</Select>
  <Input label="المبلغ المقبوض *" type="number" min="0.0001" max={editing?undefined:chosen?.remaining_amount} required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Input label="نسبة العمولة %" type="number" min="0" max="100" step="0.01" value={form.commission_percentage} onChange={e=>setForm({...form,commission_percentage:e.target.value})}/>
  <Select label="طريقة الدفع" value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}>{Object.entries(paymentLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><div className="calc-box"><span>العمولة: <strong>{money(calc.commission)}</strong></span><span>الصافي: <strong>{money(calc.net)}</strong></span></div>
  <div className="full"><Textarea label="ملاحظات" rows={3} value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></div>
 </div><div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>إلغاء</Button><Button type="submit" loading={saving}>حفظ العملية</Button></div></Form></Modal>
 <Modal open={!!cancel} title="إلغاء عملية القبض" onClose={()=>setCancel(null)} width={520}><Textarea label="سبب الإلغاء" rows={3} value={reason} onChange={e=>setReason(e.target.value)}/><div className="warning-box">سيتم إلغاء العملية وإعادة احتساب المبلغ المدفوع والمتبقي والعمولات تلقائياً.</div><div className="modal-actions"><Button variant="secondary" onClick={()=>setCancel(null)}>تراجع</Button><Button variant="danger" loading={saving} onClick={doCancel}>تأكيد الإلغاء</Button></div></Modal>
 </>;
}
