import React, { ChangeEvent, useEffect, useState } from 'react';
import { Building2, Coins, DatabaseBackup, Save } from 'lucide-react';
import { useAuth } from '../components/AuthContext';
import { Button, Card, Form, Input, PageHeader, Select } from '../components/ui';
import { useToast } from '../components/Toast';

export default function SettingsPage(){
 const {settings,refreshSettings,money,can}=useAuth();const toast=useToast();const [form,setForm]=useState<any>(settings),[saving,setSaving]=useState(false),[tab,setTab]=useState<'organization'|'currency'|'backup'>('organization');
 useEffect(()=>setForm(settings),[settings]);
 const save=async()=>{setSaving(true);try{await window.nexora.settings.update(form);await refreshSettings();toast.success('تم حفظ الإعدادات وتطبيقها على النظام.')}catch(e:any){toast.error(e.message)}finally{setSaving(false)}};
 const logo=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setForm({...form,logo_data:String(reader.result)});reader.readAsDataURL(file)};
 const backup=async()=>{try{const r=await window.nexora.backup.create();if(!r.canceled)toast.success('تم حفظ النسخة الاحتياطية بنجاح.')}catch(e:any){toast.error(e.message)}};
 const restore=async()=>{if(!confirm('سيتم استبدال قاعدة البيانات الحالية. هل تريد المتابعة؟'))return;try{const r=await window.nexora.backup.restore();if(!r.canceled){alert('تمت الاستعادة. سيتم العودة إلى شاشة الدخول.');window.location.reload();}}catch(e:any){toast.error(e.message)}};
 return <><PageHeader title="الإعدادات" subtitle="إعداد بيانات المؤسسة والعملة والنسخ الاحتياطي" actions={can('settings','edit')&&tab!=='backup'&&<Button onClick={()=>void save()} loading={saving}><Save size={17}/>حفظ التغييرات</Button>}/>
 <div className="settings-layout"><Card className="settings-nav"><button className={tab==='organization'?'active':''} onClick={()=>setTab('organization')}><Building2/>بيانات المؤسسة</button><button className={tab==='currency'?'active':''} onClick={()=>setTab('currency')}><Coins/>العملة والتنسيق</button><button className={tab==='backup'?'active':''} onClick={()=>setTab('backup')}><DatabaseBackup/>النسخ الاحتياطي</button></Card>
 <Card className="settings-content">{tab==='organization'&&<Form onSubmit={save}><div className="settings-heading"><Building2/><div><h2>بيانات المؤسسة</h2><p>تظهر هذه البيانات في الإيصالات والتقارير.</p></div></div><div className="form-grid"><Input label="اسم المؤسسة" value={form.organization_name||''} onChange={e=>setForm({...form,organization_name:e.target.value})}/><Input label="رقم الهاتف" value={form.organization_phone||''} onChange={e=>setForm({...form,organization_phone:e.target.value})}/><Input label="البريد الإلكتروني" type="email" value={form.organization_email||''} onChange={e=>setForm({...form,organization_email:e.target.value})}/><Input label="الرقم الضريبي" value={form.tax_number||''} onChange={e=>setForm({...form,tax_number:e.target.value})}/><div className="full"><Input label="العنوان" value={form.organization_address||''} onChange={e=>setForm({...form,organization_address:e.target.value})}/></div><div className="full logo-upload"><label>شعار المؤسسة</label><input type="file" accept="image/*" onChange={logo}/>{form.logo_data&&<img src={form.logo_data} alt="الشعار"/>}</div></div></Form>}
 {tab==='currency'&&<Form onSubmit={save}><div className="settings-heading"><Coins/><div><h2>العملة وتنسيق الأرقام</h2><p>التغيير يؤثر على العرض فقط ولا يحوّل القيم القديمة.</p></div></div><div className="form-grid"><Input label="اسم العملة" value={form.currency_name||''} onChange={e=>setForm({...form,currency_name:e.target.value})}/><Input label="الكود الدولي" maxLength={3} value={form.currency_code||''} onChange={e=>setForm({...form,currency_code:e.target.value.toUpperCase()})}/><Input label="رمز العملة" value={form.currency_symbol||''} onChange={e=>setForm({...form,currency_symbol:e.target.value})}/><Select label="مكان الرمز" value={form.symbol_position||'after'} onChange={e=>setForm({...form,symbol_position:e.target.value})}><option value="after">بعد المبلغ</option><option value="before">قبل المبلغ</option></Select><Input label="المنازل العشرية" type="number" min="0" max="4" value={form.decimal_places??0} onChange={e=>setForm({...form,decimal_places:Number(e.target.value)})}/><Input label="فاصل الآلاف" value={form.thousands_separator||','} onChange={e=>setForm({...form,thousands_separator:e.target.value})}/><Input label="الفاصل العشري" value={form.decimal_separator||'.'} onChange={e=>setForm({...form,decimal_separator:e.target.value})}/><Input label="بادئة الإيصال" value={form.receipt_prefix||'REC'} onChange={e=>setForm({...form,receipt_prefix:e.target.value.toUpperCase()})}/><Input label="بادئة سند التسليم" value={form.settlement_prefix||'SET'} onChange={e=>setForm({...form,settlement_prefix:e.target.value.toUpperCase()})}/><div className="full currency-preview"><span>معاينة العرض</span><strong>{money(1250000.5)}</strong><small>لن يتم تحويل أي قيمة محفوظة عند تغيير العملة.</small></div></div></Form>}
 {tab==='backup'&&<div><div className="settings-heading"><DatabaseBackup/><div><h2>النسخ الاحتياطي والاستعادة</h2><p>احفظ نسخة كاملة من قاعدة البيانات أو استعد نسخة سابقة.</p></div></div><div className="backup-grid"><div><h3>إنشاء نسخة احتياطية</h3><p>يحفظ جميع المستخدمين والمندوبين والعملاء والعمليات والإعدادات في ملف SQLite.</p><Button onClick={()=>void backup()}>اختيار مكان الحفظ</Button></div><div className="danger-zone"><h3>استعادة نسخة احتياطية</h3><p>سيتم استبدال البيانات الحالية بالكامل، مع إنشاء نسخة أمان تلقائية قبل الاستعادة.</p><Button variant="danger" onClick={()=>void restore()}>اختيار ملف واستعادة</Button></div></div><div className="info-box">مكان قاعدة البيانات الفعلية تحدده بيئة Electron داخل مجلد بيانات التطبيق للمستخدم، ولا توجد بيانات تجريبية مضمنة.</div></div>}</Card></div></>;
}
