-- Nexora Collect online database for Supabase
-- Run this file once in Supabase SQL Editor or with `supabase db push`.

create extension if not exists citext;

create sequence if not exists public.representative_code_seq start 1;
create sequence if not exists public.customer_code_seq start 1;
create sequence if not exists public.receivable_number_seq start 1;
create sequence if not exists public.collection_receipt_seq start 1;
create sequence if not exists public.settlement_number_seq start 1;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  username citext not null unique,
  full_name text not null,
  role text not null default 'user' check (role in ('admin','user','viewer')),
  permissions jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  representative_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  id bigint primary key default 1 check (id = 1),
  organization_name text not null default 'نكسورا للتحصيل',
  organization_phone text default '',
  organization_address text default '',
  organization_email text default '',
  tax_number text default '',
  logo_data text default '',
  currency_name text not null default 'الدينار العراقي',
  currency_code text not null default 'IQD',
  currency_symbol text not null default 'د.ع',
  symbol_position text not null default 'after' check (symbol_position in ('before','after')),
  decimal_places integer not null default 0 check (decimal_places between 0 and 4),
  thousands_separator text not null default ',',
  decimal_separator text not null default '.',
  date_format text not null default 'yyyy-MM-dd',
  receipt_prefix text not null default 'REC',
  settlement_prefix text not null default 'SET',
  updated_at timestamptz not null default now()
);

create table if not exists public.representatives (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  phone text default '',
  address text default '',
  email text default '',
  default_commission numeric(7,4) not null default 0 check (default_commission between 0 and 100),
  status text not null default 'active' check (status in ('active','inactive')),
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_representative_fk') then
    alter table public.profiles add constraint profiles_representative_fk foreign key (representative_id) references public.representatives(id) on delete set null;
  end if;
end $$;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  phone text default '',
  address text default '',
  area text default '',
  representative_id bigint references public.representatives(id) on delete set null,
  commission_percentage numeric(7,4) check (commission_percentage is null or commission_percentage between 0 and 100),
  status text not null default 'active' check (status in ('active','inactive')),
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_assignments (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  representative_id bigint references public.representatives(id) on delete set null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  changed_by bigint references public.profiles(id) on delete set null,
  notes text default ''
);

create table if not exists public.receivables (
  id bigint generated by default as identity primary key,
  number text not null unique,
  customer_id bigint not null references public.customers(id) on delete restrict,
  representative_id bigint references public.representatives(id) on delete set null,
  description text not null,
  original_amount numeric(18,4) not null check (original_amount >= 0),
  paid_amount numeric(18,4) not null default 0,
  remaining_amount numeric(18,4) not null default 0,
  commission_percentage numeric(7,4) not null default 0 check (commission_percentage between 0 and 100),
  issue_date date not null default current_date,
  due_date date,
  status text not null default 'unpaid' check (status in ('unpaid','partial','paid','overdue','cancelled')),
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  operation_token uuid unique,
  receipt_number text not null unique,
  customer_id bigint not null references public.customers(id) on delete restrict,
  receivable_id bigint not null references public.receivables(id) on delete restrict,
  representative_id bigint references public.representatives(id) on delete set null,
  amount numeric(18,4) not null check (amount > 0),
  commission_percentage numeric(7,4) not null check (commission_percentage between 0 and 100),
  commission_amount numeric(18,4) not null,
  net_amount numeric(18,4) not null,
  collection_date date not null default current_date,
  payment_method text not null default 'cash',
  notes text default '',
  status text not null default 'active' check (status in ('active','cancelled')),
  cancelled_at timestamptz,
  cancelled_by bigint references public.profiles(id) on delete set null,
  created_by bigint references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settlements (
  id bigint generated by default as identity primary key,
  number text not null unique,
  representative_id bigint not null references public.representatives(id) on delete restrict,
  amount numeric(18,4) not null check (amount > 0),
  settlement_date date not null default current_date,
  payment_method text not null default 'cash',
  reference_number text default '',
  received_by text default '',
  notes text default '',
  created_by bigint references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.profiles(id) on delete set null,
  username text not null default 'system',
  action text not null,
  entity_type text not null,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  created_at timestamptz not null default now()
);

insert into public.settings (id) values (1) on conflict (id) do nothing;

create index if not exists idx_profiles_auth_user on public.profiles(auth_user_id);
create index if not exists idx_customers_rep on public.customers(representative_id);
create index if not exists idx_receivables_customer on public.receivables(customer_id);
create index if not exists idx_receivables_rep on public.receivables(representative_id);
create index if not exists idx_collections_date on public.collections(collection_date);
create index if not exists idx_collections_customer on public.collections(customer_id);
create index if not exists idx_collections_rep on public.collections(representative_id);
create index if not exists idx_settlements_rep on public.settlements(representative_id);
create index if not exists idx_audit_created on public.audit_logs(created_at desc);

create or replace function public.current_profile_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select p.id from public.profiles p where p.auth_user_id = auth.uid() and p.active = true limit 1
$$;

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select p.role from public.profiles p where p.auth_user_id = auth.uid() and p.active = true limit 1
$$;

create or replace function public.current_representative_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select p.representative_id from public.profiles p where p.auth_user_id = auth.uid() and p.active = true limit 1
$$;

create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(select 1 from public.profiles p where p.auth_user_id = auth.uid() and p.active = true)
$$;

create or replace function public.has_permission(p_page text, p_action text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    p.role = 'admin' or
    case when p.role = 'viewer' and p_action in ('create','edit','delete') then false
         else coalesce((p.permissions -> p_page ->> p_action)::boolean, false)
    end,
    false
  )
  from public.profiles p
  where p.auth_user_id = auth.uid() and p.active = true
  limit 1
$$;

create or replace function public.can_access_representative(p_representative_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    p.role = 'admin' or p.representative_id is null or p.representative_id = p_representative_id,
    false
  )
  from public.profiles p
  where p.auth_user_id = auth.uid() and p.active = true
  limit 1
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.assign_codes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_prefix text;
begin
  if tg_table_name = 'representatives' and coalesce(new.code,'') = '' then
    new.code := 'REP-' || lpad(nextval('public.representative_code_seq')::text, 6, '0');
  elsif tg_table_name = 'customers' and coalesce(new.code,'') = '' then
    new.code := 'CUS-' || lpad(nextval('public.customer_code_seq')::text, 6, '0');
  elsif tg_table_name = 'receivables' and coalesce(new.number,'') = '' then
    new.number := 'INV-' || lpad(nextval('public.receivable_number_seq')::text, 7, '0');
  elsif tg_table_name = 'collections' and coalesce(new.receipt_number,'') = '' then
    select receipt_prefix into v_prefix from public.settings where id = 1;
    new.receipt_number := coalesce(nullif(v_prefix,''),'REC') || '-' || lpad(nextval('public.collection_receipt_seq')::text, 7, '0');
  elsif tg_table_name = 'settlements' and coalesce(new.number,'') = '' then
    select settlement_prefix into v_prefix from public.settings where id = 1;
    new.number := coalesce(nullif(v_prefix,''),'SET') || '-' || lpad(nextval('public.settlement_number_seq')::text, 7, '0');
  end if;
  return new;
end;
$$;

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_profile public.profiles;
  v_action text;
  v_old jsonb;
  v_new jsonb;
  v_id text;
begin
  select * into v_profile from public.profiles p where p.auth_user_id = auth.uid() limit 1;
  v_action := lower(tg_op);
  if tg_op = 'INSERT' then
    v_new := to_jsonb(new); v_id := new.id::text;
  elsif tg_op = 'UPDATE' then
    v_old := to_jsonb(old); v_new := to_jsonb(new); v_id := new.id::text;
  else
    v_old := to_jsonb(old); v_id := old.id::text;
  end if;
  insert into public.audit_logs(user_id,username,action,entity_type,entity_id,old_values,new_values)
  values(v_profile.id,coalesce(v_profile.username::text,'system'),v_action,tg_argv[0],v_id,v_old,v_new);
  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

create or replace function public.refresh_receivable(p_receivable_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_original numeric;
  v_cancelled boolean;
  v_due date;
  v_paid numeric;
  v_remaining numeric;
  v_status text;
begin
  select original_amount, status = 'cancelled', due_date
    into v_original, v_cancelled, v_due
  from public.receivables where id = p_receivable_id;
  if not found then return; end if;
  select coalesce(sum(amount),0) into v_paid
  from public.collections where receivable_id = p_receivable_id and status = 'active';
  v_remaining := greatest(0, v_original - v_paid);
  if v_cancelled then v_status := 'cancelled';
  elsif v_remaining <= 0 then v_status := 'paid';
  elsif v_paid > 0 then v_status := 'partial';
  elsif v_due is not null and v_due < current_date then v_status := 'overdue';
  else v_status := 'unpaid'; end if;
  update public.receivables
     set paid_amount = v_paid, remaining_amount = v_remaining, status = v_status, updated_at = now()
   where id = p_receivable_id;
end;
$$;

create or replace function public.collections_refresh_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op in ('UPDATE','DELETE') then perform public.refresh_receivable(old.receivable_id); end if;
  if tg_op in ('INSERT','UPDATE') then perform public.refresh_receivable(new.receivable_id); end if;
  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

create or replace function public.refresh_overdue_receivables()
returns void
language sql
security definer
set search_path = ''
as $$
  update public.receivables
     set status = case
       when remaining_amount <= 0 then 'paid'
       when paid_amount > 0 then 'partial'
       when due_date is not null and due_date < current_date then 'overdue'
       else 'unpaid'
     end,
     updated_at = now()
   where status <> 'cancelled'
$$;

create or replace function public.create_collection(p_values jsonb)
returns public.collections
language plpgsql
security invoker
as $$
declare
  v_rec public.receivables;
  v_existing public.collections;
  v_amount numeric;
  v_pct numeric;
  v_commission numeric;
  v_row public.collections;
begin
  if p_values ? 'operation_token' and nullif(p_values->>'operation_token','') is not null then
    select * into v_existing from public.collections where operation_token = (p_values->>'operation_token')::uuid;
    if found then return v_existing; end if;
  end if;
  select * into v_rec from public.receivables where id = (p_values->>'receivable_id')::bigint for update;
  if not found or v_rec.status = 'cancelled' then raise exception 'المبلغ المستحق غير موجود أو ملغى.'; end if;
  v_amount := (p_values->>'amount')::numeric;
  if v_amount <= 0 then raise exception 'المبلغ المقبوض يجب أن يكون أكبر من صفر.'; end if;
  if v_amount > v_rec.remaining_amount then raise exception 'المبلغ المقبوض أكبر من المبلغ المتبقي.'; end if;
  v_pct := coalesce(nullif(p_values->>'commission_percentage','')::numeric, v_rec.commission_percentage);
  if v_pct < 0 or v_pct > 100 then raise exception 'نسبة العمولة يجب أن تكون بين 0 و100.'; end if;
  v_commission := round(v_amount * v_pct / 100, 4);
  insert into public.collections(operation_token,receipt_number,customer_id,receivable_id,representative_id,amount,commission_percentage,commission_amount,net_amount,collection_date,payment_method,notes,status,created_by)
  values(
    nullif(p_values->>'operation_token','')::uuid,
    coalesce(p_values->>'receipt_number',''),
    v_rec.customer_id,
    v_rec.id,
    v_rec.representative_id,
    v_amount,
    v_pct,
    v_commission,
    v_amount - v_commission,
    coalesce(nullif(p_values->>'collection_date','')::date,current_date),
    coalesce(nullif(p_values->>'payment_method',''),'cash'),
    coalesce(p_values->>'notes',''),
    'active',
    public.current_profile_id()
  ) returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.update_collection(p_id bigint, p_values jsonb)
returns public.collections
language plpgsql
security invoker
as $$
declare
  v_old public.collections;
  v_rec public.receivables;
  v_amount numeric;
  v_pct numeric;
  v_commission numeric;
  v_available numeric;
  v_row public.collections;
begin
  select * into v_old from public.collections where id = p_id for update;
  if not found then raise exception 'عملية القبض غير موجودة.'; end if;
  if v_old.status = 'cancelled' then raise exception 'لا يمكن تعديل عملية ملغاة.'; end if;
  select * into v_rec from public.receivables where id = coalesce(nullif(p_values->>'receivable_id','')::bigint,v_old.receivable_id) for update;
  if not found or v_rec.status = 'cancelled' then raise exception 'المبلغ المستحق غير موجود أو ملغى.'; end if;
  v_amount := coalesce(nullif(p_values->>'amount','')::numeric,v_old.amount);
  v_available := v_rec.remaining_amount + case when v_rec.id = v_old.receivable_id then v_old.amount else 0 end;
  if v_amount <= 0 then raise exception 'المبلغ المقبوض يجب أن يكون أكبر من صفر.'; end if;
  if v_amount > v_available then raise exception 'المبلغ المقبوض أكبر من المبلغ المتبقي.'; end if;
  v_pct := coalesce(nullif(p_values->>'commission_percentage','')::numeric,v_rec.commission_percentage);
  if v_pct < 0 or v_pct > 100 then raise exception 'نسبة العمولة يجب أن تكون بين 0 و100.'; end if;
  v_commission := round(v_amount * v_pct / 100, 4);
  update public.collections set
    receipt_number = coalesce(nullif(p_values->>'receipt_number',''),receipt_number),
    customer_id = v_rec.customer_id,
    receivable_id = v_rec.id,
    representative_id = v_rec.representative_id,
    amount = v_amount,
    commission_percentage = v_pct,
    commission_amount = v_commission,
    net_amount = v_amount - v_commission,
    collection_date = coalesce(nullif(p_values->>'collection_date','')::date,collection_date),
    payment_method = coalesce(nullif(p_values->>'payment_method',''),payment_method),
    notes = coalesce(p_values->>'notes',notes),
    updated_at = now()
  where id = p_id returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.cancel_collection(p_id bigint, p_reason text default '')
returns boolean
language plpgsql
security invoker
as $$
begin
  update public.collections
     set status='cancelled', cancelled_at=now(), cancelled_by=public.current_profile_id(),
         notes=concat_ws(E'\n',nullif(notes,''),case when coalesce(p_reason,'')<>'' then 'سبب الإلغاء: '||p_reason end), updated_at=now()
   where id=p_id and status='active';
  if not found then raise exception 'عملية القبض غير موجودة أو ملغاة مسبقاً.'; end if;
  return true;
end;
$$;

create or replace function public.create_settlement(p_values jsonb)
returns public.settlements
language plpgsql
security invoker
as $$
declare
  v_rep bigint;
  v_amount numeric;
  v_due numeric;
  v_delivered numeric;
  v_row public.settlements;
begin
  v_rep := (p_values->>'representative_id')::bigint;
  v_amount := (p_values->>'amount')::numeric;
  if v_amount <= 0 then raise exception 'المبلغ المسلم يجب أن يكون أكبر من صفر.'; end if;
  select coalesce(sum(net_amount),0) into v_due from public.collections where representative_id=v_rep and status='active';
  select coalesce(sum(amount),0) into v_delivered from public.settlements where representative_id=v_rep;
  if v_amount > (v_due-v_delivered) then raise exception 'المبلغ المسلم أكبر من الرصيد المستحق على المندوب.'; end if;
  insert into public.settlements(number,representative_id,amount,settlement_date,payment_method,reference_number,received_by,notes,created_by)
  values(coalesce(p_values->>'number',''),v_rep,v_amount,coalesce(nullif(p_values->>'settlement_date','')::date,current_date),coalesce(nullif(p_values->>'payment_method',''),'cash'),coalesce(p_values->>'reference_number',''),coalesce(nullif(p_values->>'received_by',''),(select full_name from public.profiles where id=public.current_profile_id())),coalesce(p_values->>'notes',''),public.current_profile_id())
  returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.transfer_customer(p_customer_id bigint, p_representative_id bigint, p_notes text default '')
returns public.customers
language plpgsql
security invoker
as $$
declare
  v_row public.customers;
begin
  update public.customer_assignments set ended_at=now()
   where customer_id=p_customer_id and ended_at is null;
  insert into public.customer_assignments(customer_id,representative_id,changed_by,notes)
  values(p_customer_id,p_representative_id,public.current_profile_id(),coalesce(p_notes,''));
  update public.customers set representative_id=p_representative_id,updated_at=now() where id=p_customer_id returning * into v_row;
  if not found then raise exception 'العميل غير موجود.'; end if;
  return v_row;
end;
$$;

create or replace function public.remove_representative(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_count bigint;
begin
  if not public.has_permission('representatives','delete') then raise exception 'ليس لديك صلاحية حذف المندوب.'; end if;
  if not public.can_access_representative(p_id) then raise exception 'ليس لديك صلاحية الوصول إلى هذا المندوب.'; end if;
  if not exists(select 1 from public.representatives where id=p_id) then raise exception 'المندوب غير موجود.'; end if;
  select (select count(*) from public.receivables where representative_id=p_id) +
         (select count(*) from public.collections where representative_id=p_id) +
         (select count(*) from public.settlements where representative_id=p_id) into v_count;
  if v_count>0 then
    update public.representatives set status='inactive',updated_at=now() where id=p_id;
    return jsonb_build_object('deactivated',true);
  end if;
  update public.customers set representative_id=null,updated_at=now() where representative_id=p_id;
  delete from public.representatives where id=p_id;
  return jsonb_build_object('deactivated',false);
end;
$$;

create or replace function public.remove_customer(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count bigint;
  v_rep bigint;
begin
  if not public.has_permission('customers','delete') then raise exception 'ليس لديك صلاحية حذف العميل.'; end if;
  select representative_id into v_rep from public.customers where id=p_id;
  if not found then raise exception 'العميل غير موجود.'; end if;
  if not public.can_access_representative(v_rep) then raise exception 'ليس لديك صلاحية الوصول إلى هذا العميل.'; end if;
  select (select count(*) from public.receivables where customer_id=p_id) +
         (select count(*) from public.collections where customer_id=p_id) into v_count;
  if v_count>0 then
    update public.customers set status='inactive',updated_at=now() where id=p_id;
    return jsonb_build_object('deactivated',true);
  end if;
  delete from public.customers where id=p_id;
  return jsonb_build_object('deactivated',false);
end;
$$;

create or replace function public.remove_receivable(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count bigint;
  v_rep bigint;
begin
  if not public.has_permission('receivables','delete') then raise exception 'ليس لديك صلاحية حذف المبلغ المستحق.'; end if;
  select representative_id into v_rep from public.receivables where id=p_id;
  if not found then raise exception 'المبلغ المستحق غير موجود.'; end if;
  if not public.can_access_representative(v_rep) then raise exception 'ليس لديك صلاحية الوصول إلى هذا المبلغ.'; end if;
  select count(*) into v_count from public.collections where receivable_id=p_id;
  if v_count>0 then
    update public.receivables set status='cancelled',updated_at=now() where id=p_id;
    return jsonb_build_object('cancelled',true);
  end if;
  delete from public.receivables where id=p_id;
  return jsonb_build_object('cancelled',false);
end;
$$;

create or replace function public.dashboard_data()
returns jsonb
language sql
security definer
set search_path = ''
as $$
select case when public.has_permission('dashboard','view') then jsonb_build_object(
  'totals', jsonb_build_object(
    'representatives',(select count(*) from public.representatives r where r.status='active' and public.can_access_representative(r.id)),
    'customers',(select count(*) from public.customers c where c.status='active' and public.can_access_representative(c.representative_id)),
    'receivables',(select coalesce(sum(rv.original_amount),0) from public.receivables rv where rv.status<>'cancelled' and public.can_access_representative(rv.representative_id)),
    'collected',(select coalesce(sum(cl.amount),0) from public.collections cl where cl.status='active' and public.can_access_representative(cl.representative_id)),
    'remaining',(select coalesce(sum(rv.remaining_amount),0) from public.receivables rv where rv.status<>'cancelled' and public.can_access_representative(rv.representative_id)),
    'commissions',(select coalesce(sum(cl.commission_amount),0) from public.collections cl where cl.status='active' and public.can_access_representative(cl.representative_id)),
    'net',(select coalesce(sum(cl.net_amount),0) from public.collections cl where cl.status='active' and public.can_access_representative(cl.representative_id)),
    'today',(select coalesce(sum(cl.amount),0) from public.collections cl where cl.status='active' and cl.collection_date=current_date and public.can_access_representative(cl.representative_id)),
    'month',(select coalesce(sum(cl.amount),0) from public.collections cl where cl.status='active' and date_trunc('month',cl.collection_date)=date_trunc('month',current_date) and public.can_access_representative(cl.representative_id))
  ),
  'recent',coalesce((select jsonb_agg(x order by x.collection_date desc,x.id desc) from (
    select cl.id,cl.receipt_number,cl.amount,cl.commission_amount,cl.net_amount,cl.collection_date,cl.payment_method,cu.name customer_name,r.name representative_name
    from public.collections cl
    join public.customers cu on cu.id=cl.customer_id
    left join public.representatives r on r.id=cl.representative_id
    where cl.status='active' and public.can_access_representative(cl.representative_id)
    order by cl.collection_date desc,cl.id desc limit 10
  ) x),'[]'::jsonb),
  'trend',coalesce((select jsonb_agg(x order by x.date) from (
    select cl.collection_date date,sum(cl.amount) amount
    from public.collections cl
    where cl.status='active' and cl.collection_date>=current_date-29 and public.can_access_representative(cl.representative_id)
    group by cl.collection_date
  ) x),'[]'::jsonb),
  'topReps',coalesce((select jsonb_agg(x order by x.amount desc) from (
    select r.name,coalesce(sum(c.amount),0) amount
    from public.representatives r
    left join public.collections c on c.representative_id=r.id and c.status='active'
    where public.can_access_representative(r.id)
    group by r.id,r.name order by amount desc limit 5
  ) x),'[]'::jsonb),
  'topDebtors',coalesce((select jsonb_agg(x order by x.remaining desc) from (
    select c.name,coalesce(sum(rv.remaining_amount),0) remaining
    from public.customers c
    left join public.receivables rv on rv.customer_id=c.id and rv.status<>'cancelled'
    where public.can_access_representative(c.representative_id)
    group by c.id,c.name having coalesce(sum(rv.remaining_amount),0)>0
    order by remaining desc limit 5
  ) x),'[]'::jsonb)
) else null end
$$;

create or replace function public.reset_nexora_sequences()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform setval(pg_get_serial_sequence('public.profiles','id'),coalesce((select max(id) from public.profiles),1),true);
  perform setval(pg_get_serial_sequence('public.representatives','id'),coalesce((select max(id) from public.representatives),1),true);
  perform setval(pg_get_serial_sequence('public.customers','id'),coalesce((select max(id) from public.customers),1),true);
  perform setval(pg_get_serial_sequence('public.customer_assignments','id'),coalesce((select max(id) from public.customer_assignments),1),true);
  perform setval(pg_get_serial_sequence('public.receivables','id'),coalesce((select max(id) from public.receivables),1),true);
  perform setval(pg_get_serial_sequence('public.collections','id'),coalesce((select max(id) from public.collections),1),true);
  perform setval(pg_get_serial_sequence('public.settlements','id'),coalesce((select max(id) from public.settlements),1),true);
  perform setval(pg_get_serial_sequence('public.audit_logs','id'),coalesce((select max(id) from public.audit_logs),1),true);
  perform setval('public.representative_code_seq',greatest(coalesce((select max(id) from public.representatives),1),1),true);
  perform setval('public.customer_code_seq',greatest(coalesce((select max(id) from public.customers),1),1),true);
  perform setval('public.receivable_number_seq',greatest(coalesce((select max(id) from public.receivables),1),1),true);
  perform setval('public.collection_receipt_seq',greatest(coalesce((select max(id) from public.collections),1),1),true);
  perform setval('public.settlement_number_seq',greatest(coalesce((select max(id) from public.settlements),1),1),true);
end;
$$;

-- Views use the caller's RLS policies.
create or replace view public.representative_summaries with (security_invoker=true) as
select r.*,
  (select count(*) from public.customers c where c.representative_id=r.id and c.status='active') customer_count,
  (select coalesce(sum(amount),0) from public.collections c where c.representative_id=r.id and c.status='active') collected,
  (select coalesce(sum(commission_amount),0) from public.collections c where c.representative_id=r.id and c.status='active') commissions,
  (select coalesce(sum(net_amount),0) from public.collections c where c.representative_id=r.id and c.status='active') net,
  (select coalesce(sum(amount),0) from public.settlements s where s.representative_id=r.id) settlements
from public.representatives r;

create or replace view public.customer_summaries with (security_invoker=true) as
select c.*,r.name representative_name,
  (select coalesce(sum(original_amount),0) from public.receivables rv where rv.customer_id=c.id and rv.status<>'cancelled') total_receivable,
  (select coalesce(sum(amount),0) from public.collections cl where cl.customer_id=c.id and cl.status='active') collected,
  (select coalesce(sum(remaining_amount),0) from public.receivables rv where rv.customer_id=c.id and rv.status<>'cancelled') remaining
from public.customers c left join public.representatives r on r.id=c.representative_id;

create or replace view public.receivable_details with (security_invoker=true) as
select rv.*,cu.name customer_name,r.name representative_name
from public.receivables rv join public.customers cu on cu.id=rv.customer_id left join public.representatives r on r.id=rv.representative_id;

create or replace view public.collection_details with (security_invoker=true) as
select cl.*,cu.name customer_name,cu.phone customer_phone,r.name representative_name,rv.number receivable_number,rv.description receivable_description,p.full_name created_by_name
from public.collections cl join public.customers cu on cu.id=cl.customer_id left join public.representatives r on r.id=cl.representative_id join public.receivables rv on rv.id=cl.receivable_id left join public.profiles p on p.id=cl.created_by;

create or replace view public.settlement_details with (security_invoker=true) as
select s.*,r.name representative_name,p.full_name created_by_name
from public.settlements s join public.representatives r on r.id=s.representative_id left join public.profiles p on p.id=s.created_by;

create or replace view public.customer_assignment_details with (security_invoker=true) as
select a.*,r.name representative_name,p.full_name changed_by_name
from public.customer_assignments a left join public.representatives r on r.id=a.representative_id left join public.profiles p on p.id=a.changed_by;

-- Triggers
drop trigger if exists trg_representatives_code on public.representatives;
drop trigger if exists trg_customers_code on public.customers;
drop trigger if exists trg_receivables_code on public.receivables;
drop trigger if exists trg_collections_code on public.collections;
drop trigger if exists trg_settlements_code on public.settlements;
drop trigger if exists trg_profiles_touch on public.profiles;
drop trigger if exists trg_settings_touch on public.settings;
drop trigger if exists trg_representatives_touch on public.representatives;
drop trigger if exists trg_customers_touch on public.customers;
drop trigger if exists trg_receivables_touch on public.receivables;
drop trigger if exists trg_collections_touch on public.collections;
drop trigger if exists trg_settlements_touch on public.settlements;
drop trigger if exists trg_collections_refresh on public.collections;
drop trigger if exists trg_audit_representatives on public.representatives;
drop trigger if exists trg_audit_customers on public.customers;
drop trigger if exists trg_audit_receivables on public.receivables;
drop trigger if exists trg_audit_collections on public.collections;
drop trigger if exists trg_audit_settlements on public.settlements;
drop trigger if exists trg_audit_settings on public.settings;
create trigger trg_representatives_code before insert on public.representatives for each row execute function public.assign_codes();
create trigger trg_customers_code before insert on public.customers for each row execute function public.assign_codes();
create trigger trg_receivables_code before insert on public.receivables for each row execute function public.assign_codes();
create trigger trg_collections_code before insert on public.collections for each row execute function public.assign_codes();
create trigger trg_settlements_code before insert on public.settlements for each row execute function public.assign_codes();

create trigger trg_profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
create trigger trg_settings_touch before update on public.settings for each row execute function public.touch_updated_at();
create trigger trg_representatives_touch before update on public.representatives for each row execute function public.touch_updated_at();
create trigger trg_customers_touch before update on public.customers for each row execute function public.touch_updated_at();
create trigger trg_receivables_touch before update on public.receivables for each row execute function public.touch_updated_at();
create trigger trg_collections_touch before update on public.collections for each row execute function public.touch_updated_at();
create trigger trg_settlements_touch before update on public.settlements for each row execute function public.touch_updated_at();

create trigger trg_collections_refresh after insert or update or delete on public.collections for each row execute function public.collections_refresh_trigger();

create trigger trg_audit_representatives after insert or update or delete on public.representatives for each row execute function public.audit_row_change('representative');
create trigger trg_audit_customers after insert or update or delete on public.customers for each row execute function public.audit_row_change('customer');
create trigger trg_audit_receivables after insert or update or delete on public.receivables for each row execute function public.audit_row_change('receivable');
create trigger trg_audit_collections after insert or update or delete on public.collections for each row execute function public.audit_row_change('collection');
create trigger trg_audit_settlements after insert or update or delete on public.settlements for each row execute function public.audit_row_change('settlement');
create trigger trg_audit_settings after update on public.settings for each row execute function public.audit_row_change('settings');

-- Row Level Security
drop policy if exists profiles_select on public.profiles;
drop policy if exists settings_select on public.settings;
drop policy if exists settings_update on public.settings;
drop policy if exists reps_select on public.representatives;
drop policy if exists reps_insert on public.representatives;
drop policy if exists reps_update on public.representatives;
drop policy if exists reps_delete on public.representatives;
drop policy if exists customers_select on public.customers;
drop policy if exists customers_insert on public.customers;
drop policy if exists customers_update on public.customers;
drop policy if exists customers_delete on public.customers;
drop policy if exists assignments_select on public.customer_assignments;
drop policy if exists assignments_insert on public.customer_assignments;
drop policy if exists assignments_update on public.customer_assignments;
drop policy if exists assignments_delete on public.customer_assignments;
drop policy if exists receivables_select on public.receivables;
drop policy if exists receivables_insert on public.receivables;
drop policy if exists receivables_update on public.receivables;
drop policy if exists receivables_delete on public.receivables;
drop policy if exists collections_select on public.collections;
drop policy if exists collections_insert on public.collections;
drop policy if exists collections_update on public.collections;
drop policy if exists collections_delete on public.collections;
drop policy if exists settlements_select on public.settlements;
drop policy if exists settlements_insert on public.settlements;
drop policy if exists settlements_update on public.settlements;
drop policy if exists settlements_delete on public.settlements;
drop policy if exists audit_select on public.audit_logs;
alter table public.profiles enable row level security;
alter table public.settings enable row level security;
alter table public.representatives enable row level security;
alter table public.customers enable row level security;
alter table public.customer_assignments enable row level security;
alter table public.receivables enable row level security;
alter table public.collections enable row level security;
alter table public.settlements enable row level security;
alter table public.audit_logs enable row level security;

create policy profiles_select on public.profiles for select to authenticated using (auth_user_id=auth.uid() or public.has_permission('users','view'));

create policy settings_select on public.settings for select to authenticated using (public.is_active_user());
create policy settings_update on public.settings for update to authenticated using (public.has_permission('settings','edit')) with check (public.has_permission('settings','edit'));

create policy reps_select on public.representatives for select to authenticated using ((public.has_permission('representatives','view') or public.has_permission('reports','view') or public.has_permission('balances','view')) and public.can_access_representative(id));
create policy reps_insert on public.representatives for insert to authenticated with check (public.has_permission('representatives','create'));
create policy reps_update on public.representatives for update to authenticated using (public.has_permission('representatives','edit') and public.can_access_representative(id)) with check (public.has_permission('representatives','edit'));
create policy reps_delete on public.representatives for delete to authenticated using (public.has_permission('representatives','delete'));

create policy customers_select on public.customers for select to authenticated using ((public.has_permission('customers','view') or public.has_permission('reports','view') or public.has_permission('balances','view')) and public.can_access_representative(representative_id));
create policy customers_insert on public.customers for insert to authenticated with check (public.has_permission('customers','create') and public.can_access_representative(representative_id));
create policy customers_update on public.customers for update to authenticated using (public.has_permission('customers','edit') and public.can_access_representative(representative_id)) with check (public.has_permission('customers','edit') and public.can_access_representative(representative_id));
create policy customers_delete on public.customers for delete to authenticated using (public.has_permission('customers','delete') and public.can_access_representative(representative_id));

create policy assignments_select on public.customer_assignments for select to authenticated using (public.has_permission('customers','view') and public.can_access_representative(representative_id));
create policy assignments_insert on public.customer_assignments for insert to authenticated with check ((public.has_permission('customers','create') or public.has_permission('customers','edit')) and public.can_access_representative(representative_id));
create policy assignments_update on public.customer_assignments for update to authenticated using (public.has_permission('customers','edit')) with check (public.has_permission('customers','edit'));
create policy assignments_delete on public.customer_assignments for delete to authenticated using (public.has_permission('customers','delete'));

create policy receivables_select on public.receivables for select to authenticated using ((public.has_permission('receivables','view') or public.has_permission('reports','view') or public.has_permission('balances','view')) and public.can_access_representative(representative_id));
create policy receivables_insert on public.receivables for insert to authenticated with check (public.has_permission('receivables','create') and public.can_access_representative(representative_id));
create policy receivables_update on public.receivables for update to authenticated using ((public.has_permission('receivables','edit') or public.has_permission('collections','create') or public.has_permission('collections','edit') or public.has_permission('collections','delete')) and public.can_access_representative(representative_id)) with check (public.can_access_representative(representative_id));
create policy receivables_delete on public.receivables for delete to authenticated using (public.has_permission('receivables','delete') and public.can_access_representative(representative_id));

create policy collections_select on public.collections for select to authenticated using ((public.has_permission('collections','view') or public.has_permission('reports','view') or public.has_permission('balances','view')) and public.can_access_representative(representative_id));
create policy collections_insert on public.collections for insert to authenticated with check (public.has_permission('collections','create') and public.can_access_representative(representative_id));
create policy collections_update on public.collections for update to authenticated using ((public.has_permission('collections','edit') or public.has_permission('collections','delete')) and public.can_access_representative(representative_id)) with check (public.can_access_representative(representative_id));
create policy collections_delete on public.collections for delete to authenticated using (public.has_permission('collections','delete') and public.can_access_representative(representative_id));

create policy settlements_select on public.settlements for select to authenticated using ((public.has_permission('settlements','view') or public.has_permission('reports','view') or public.has_permission('balances','view')) and public.can_access_representative(representative_id));
create policy settlements_insert on public.settlements for insert to authenticated with check (public.has_permission('settlements','create') and public.can_access_representative(representative_id));
create policy settlements_update on public.settlements for update to authenticated using (public.has_permission('settlements','edit') and public.can_access_representative(representative_id)) with check (public.has_permission('settlements','edit') and public.can_access_representative(representative_id));
create policy settlements_delete on public.settlements for delete to authenticated using (public.has_permission('settlements','delete') and public.can_access_representative(representative_id));

create policy audit_select on public.audit_logs for select to authenticated using (public.has_permission('audit','view'));

-- Grants for the Data API
revoke all on all tables in schema public from anon;
grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select,update on public.settings to authenticated;
grant select,insert,update,delete on public.representatives,public.customers,public.customer_assignments,public.receivables,public.collections,public.settlements to authenticated;
grant select on public.audit_logs to authenticated;
grant select on public.representative_summaries,public.customer_summaries,public.receivable_details,public.collection_details,public.settlement_details,public.customer_assignment_details to authenticated;
grant usage,select on all sequences in schema public to authenticated;

grant execute on function public.current_profile_id() to authenticated;
grant execute on function public.current_role() to authenticated;
grant execute on function public.current_representative_id() to authenticated;
grant execute on function public.is_active_user() to authenticated;
grant execute on function public.has_permission(text,text) to authenticated;
grant execute on function public.can_access_representative(bigint) to authenticated;
grant execute on function public.refresh_overdue_receivables() to authenticated;
grant execute on function public.create_collection(jsonb) to authenticated;
grant execute on function public.update_collection(bigint,jsonb) to authenticated;
grant execute on function public.cancel_collection(bigint,text) to authenticated;
grant execute on function public.create_settlement(jsonb) to authenticated;
grant execute on function public.transfer_customer(bigint,bigint,text) to authenticated;
grant execute on function public.remove_representative(bigint) to authenticated;
grant execute on function public.remove_customer(bigint) to authenticated;
grant execute on function public.remove_receivable(bigint) to authenticated;
grant execute on function public.dashboard_data() to authenticated;

revoke execute on function public.reset_nexora_sequences() from public,anon,authenticated;
grant execute on function public.reset_nexora_sequences() to service_role;
